<?php 


/**
 * Get Print URL
 * 
 */


function hey_printURL( $optional_id = null ){
    
    // This needs to be fixed so that this check doesn't run if an $optional_id is specified
    
    if(!get_the_ID() || !get_permalink( get_the_ID() )) 
        return;
    
    $id = $optional_id ? $optional_id : get_the_ID();
    $url = get_permalink( $id );
    $connector = strpos($url, '?') ? '&' : '?';
    $url = $url . $connector . 'view=print';

    return $url;

}





/**
 * Append the terms of multiple taxonomies to the list
 * of classes generated by post_class().
 *
 * @since 2010-07-10
 * @alter 2012-01-06
 */
function mysite_post_class( $classes, $class, $ID ) {
 
    $taxonomies = array(
        'type',
        'subject',
        'demographic',
    );
 
    $terms = get_the_terms( (int) $ID, $taxonomies );
 
    if ( is_wp_error( $terms ) || empty( $terms ) )
        return $classes;
 
    foreach ( (array) $terms as $term ) {
        if ( ! in_array( $term->slug, $classes ) )
            $classes[] = $term->slug;
    }
 
    return $classes;
}
 
add_filter( 'post_class', 'mysite_post_class', 10, 3 );


// Add to the admin_init hook of your theme functions.php file

// function add_taxonomies_to_pages() {
// 	register_taxonomy_for_object_type('post_tag', 'page');
// 	register_taxonomy_for_object_type('category', 'page');
// }

// add_action('admin_init', 'add_taxonomies_to_pages');



/****************************************************
	Add link to Taxonomy Meta Post in term edit page
****************************************************/

// add_action('edit_category_form', 'taxonomy_meta_form');
// add_action('edit_tag_form', array($this, 'taxonomy_meta_form'));
// add_action('edit_taxonomy_form', 'taxonomy_meta_form');
// add_action('edit_subject_form', 'taxonomy_meta_form');
// add_action('taxonomy_edit_form', 'taxonomy_meta_form');
add_action('subject_edit_form', 'taxonomy_meta_form');
// add_action('category_edit_form', 'taxonomy_meta_form');

function taxonomy_meta_form() {
	global $tag_ID;
	global $taxonomy;
	// global $wp_query;

	// print_r($wp_query->get_queried_object());

	$term = get_term_by('id', $tag_ID, $taxonomy);

	query_posts(array(
		'post_type' => 'tax',
		$taxonomy => $term->slug,
		'posts_per_page' => -1,
	));

	// get_template_part( 'loop', 'charts-new' );

	while ( have_posts() ) : the_post();

	edit_post_link( 'Click here to edit Taxonomy Meta', '<h1>', '</h1>', get_the_id() );
	// the_title();
	the_content();

	endwhile;
	wp_reset_query();



}




/****************************************************

****************************************************/


/**
 * Allow commas in tags. Use ` and it will be replaced with a comma
 */

// filter for tags with comma
//  replace '--' with ', ' in the output - allow tags with comma this way
//  e.g. save tag as "Fox--Peter" but display thx 2 filters like "Fox, Peter"

if(!is_admin()){ // make sure the filters are only called in the frontend

    function epi_allow_commas_in_terms($terms){
    	$delimiter = '`';
    	// $default_delimiter = _x( ',', 'tag delimiter' );
    	// 
        $filtered_terms = array();

        if( ! $terms || is_wp_error($terms) )
            return $terms;

        // print_r($terms);

        foreach($terms as $term){

			$term->name = str_replace($delimiter,', ',$term->name);
            $filtered_terms[] = $term;
        }
        
        return $filtered_terms;
    }

    if (is_user_logged_in()) {
        add_filter('get_terms', 'epi_allow_commas_in_terms');
        // add_filter('get_the_terms', 'epi_allow_commas_in_terms');
    }
}










add_action( 'admin_head', 'showhiddencustomfields' );
 
function showhiddencustomfields() {
    echo "<style type='text/css'>#postcustom .hidden { display: table-row !important; }</style>\n";
}


add_post_type_support('page', 'excerpt');

